# Generated by Django 4.0.3 on 2022-04-15 09:44

import base.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djongo.models.fields.ArrayField(model_container=base.models.Media)),
            ],
            options={
                'db_table': 'anime_recommendation',
            },
        ),
        migrations.CreateModel(
            name='MangaRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djongo.models.fields.ArrayField(model_container=base.models.Media)),
            ],
            options={
                'db_table': 'manga_recommendation',
            },
        ),
    ]
